const fs = require('fs');

function convertKeyValue(key, value) {
    // Split the value by '.' to get parts
    const parts = value.split('.');
    
    // Capitalize the first letter of each part
    const capitalizedParts = parts.map(part => part.charAt(0).toUpperCase() + part.slice(1));
    
    // Join parts without dots
    const newValue = capitalizedParts.join('');
    
    // Add the slashes and 'i' flag
    const formattedValue = `/${newValue}/i`;
    
    return { key, newValue: formattedValue };
}

function processJson(inputFile, outputFile) {
    fs.readFile(inputFile, 'utf8', (err, data) => {
        if (err) {
            console.error('Error reading the input file:', err);
            return;
        }
        
        const jsonData = JSON.parse(data);
        const newData = {};
        
        for (const [key, value] of Object.entries(jsonData)) {
            const { key: newKey, newValue } = convertKeyValue(key, value);
            newData[newKey] = newValue;
        }
        
        fs.writeFile(outputFile, JSON.stringify(newData, null, 4), 'utf8', err => {
            if (err) {
                console.error('Error writing to the output file:', err);
            } else {
                console.log('File has been written successfully');
            }
        });
    });
}

// Usage
const inputFile = '../json/eventPatterns.json';
const outputFile = '../json/autogenerated/servicePatterns.json';
processJson(inputFile, outputFile);
